version: 0.2

phases:
  install:
    commands:
      - yum install -y mariadb-server
  build:
    commands:
      - env | sort
      - echo "CREATE DATABASE ${DB_NAME} DEFAULT CHARACTER SET utf8" | mysql -u${DB_USER} -p${DB_PASSWORD} -h${DB_HOST}
      - mysql -u${DB_USER} -p${DB_PASSWORD} -h${DB_HOST} ${DB_NAME} < mysql/sqls/initialize.sql

