version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 10
    commands:
      - wget https://releases.hashicorp.com/terraform/0.12.25/terraform_0.12.25_linux_amd64.zip
      - unzip terraform_0.12.25_linux_amd64.zip
      - mv terraform /usr/local/bin/terraform
      - docker --version
      - python --version
      - terraform --version
      #- cd ./lambda
      #- npm install
      #- npm run build
      #- cd ../
  pre_build:
    commands:
      - ACCOUNT_ID=${CODEBUILD_BUILD_ARN} && IFS=':' && set -- $ACCOUNT_ID && ACCOUNT_ID=$5
  build:
    commands:
      - python deploy.py $ACCOUNT_ID

