version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.7
    commands:
      - npm install
      - wget https://releases.hashicorp.com/terraform/0.12.25/terraform_0.12.25_linux_amd64.zip
      - unzip terraform_0.12.25_linux_amd64.zip
      - mv terraform /usr/local/bin/terraform
      - docker --version
      - python --version
      - terraform --version
  build:
    commands:
      - python deploy.py
      #- npm run build
      #- ./node_modules/.bin/sequelize db:migrate --env production --config server/config/config.json --migrations-path server/migrations
      #- node server/create_admin_user.js admin@example.com password 'AdminUser'

